window.esdocSearchIndex = [
  [
    "test/src/app.js~app",
    "function/index.html#static-function-App",
    "<span>App</span> <span class=\"search-result-import-path\">test/src/App.js</span>",
    "function"
  ],
  [
    "test/src/components/content/carousel/carousel.js~carousel",
    "function/index.html#static-function-Carousel",
    "<span>Carousel</span> <span class=\"search-result-import-path\">test/src/components/Content/Carousel/Carousel.js</span>",
    "function"
  ],
  [
    "test/src/imports.js~common",
    "variable/index.html#static-variable-Common",
    "<span>Common</span> <span class=\"search-result-import-path\">test/src/imports.js</span>",
    "variable"
  ],
  [
    "test/src/components/content/content.js~content",
    "function/index.html#static-function-Content",
    "<span>Content</span> <span class=\"search-result-import-path\">test/src/components/Content/Content.js</span>",
    "function"
  ],
  [
    "test/src/imports.js~faces",
    "variable/index.html#static-variable-Faces",
    "<span>Faces</span> <span class=\"search-result-import-path\">test/src/imports.js</span>",
    "variable"
  ],
  [
    "test/src/components/header/header.js~header",
    "function/index.html#static-function-Header",
    "<span>Header</span> <span class=\"search-result-import-path\">test/src/components/Header/Header.js</span>",
    "function"
  ],
  [
    "test/src/imports.js~icons",
    "variable/index.html#static-variable-Icons",
    "<span>Icons</span> <span class=\"search-result-import-path\">test/src/imports.js</span>",
    "variable"
  ],
  [
    "test/src/tools/languageselector.js~languageselector",
    "function/index.html#static-function-LanguageSelector",
    "<span>LanguageSelector</span> <span class=\"search-result-import-path\">test/src/tools/LanguageSelector.js</span>",
    "function"
  ],
  [
    "test/src/components/header/header.js~languages",
    "variable/index.html#static-variable-Languages",
    "<span>Languages</span> <span class=\"search-result-import-path\">test/src/components/Header/Header.js</span>",
    "variable"
  ],
  [
    "test/src/imports.js~moustaches",
    "variable/index.html#static-variable-Moustaches",
    "<span>Moustaches</span> <span class=\"search-result-import-path\">test/src/imports.js</span>",
    "variable"
  ],
  [
    "test/src/components/content/workspace/resultarea.js~resultarea",
    "function/index.html#static-function-ResultArea",
    "<span>ResultArea</span> <span class=\"search-result-import-path\">test/src/components/Content/WorkSpace/ResultArea.js</span>",
    "function"
  ],
  [
    "test/src/components/content/workspace/resultcompose.js~resultcompose",
    "function/index.html#static-function-ResultCompose",
    "<span>ResultCompose</span> <span class=\"search-result-import-path\">test/src/components/Content/WorkSpace/ResultCompose.js</span>",
    "function"
  ],
  [
    "test/src/components/content/workspace/face-api-func.js~getfullfacedescription",
    "function/index.html#static-function-getFullFaceDescription",
    "<span>getFullFaceDescription</span> <span class=\"search-result-import-path\">test/src/components/Content/WorkSpace/face-api-func.js</span>",
    "function"
  ],
  [
    "test/src/components/content/workspace/face-api-func.js~loadmodels",
    "function/index.html#static-function-loadModels",
    "<span>loadModels</span> <span class=\"search-result-import-path\">test/src/components/Content/WorkSpace/face-api-func.js</span>",
    "function"
  ],
  [
    "test/src/i18n.js~resources",
    "variable/index.html#static-variable-resources",
    "<span>resources</span> <span class=\"search-result-import-path\">test/src/i18n.js</span>",
    "variable"
  ],
  [
    "test/src/components/content/carousel/carousel.js~usestyles",
    "variable/index.html#static-variable-useStyles",
    "<span>useStyles</span> <span class=\"search-result-import-path\">test/src/components/Content/Carousel/Carousel.js</span>",
    "variable"
  ],
  [
    "test/src/components/header/header.js~usestyles",
    "variable/index.html#static-variable-useStyles",
    "<span>useStyles</span> <span class=\"search-result-import-path\">test/src/components/Header/Header.js</span>",
    "variable"
  ],
  [
    "test/src/tools/languageselector.js~usestyles",
    "variable/index.html#static-variable-useStyles",
    "<span>useStyles</span> <span class=\"search-result-import-path\">test/src/tools/LanguageSelector.js</span>",
    "variable"
  ],
  [
    "test/src/tools/usewidth.js~usewidth",
    "function/index.html#static-function-useWidth",
    "<span>useWidth</span> <span class=\"search-result-import-path\">test/src/tools/useWidth.js</span>",
    "function"
  ],
  [
    "src/.external-ecmascript.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "src/.external-ecmascript.js~Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "src/.external-ecmascript.js~ArrayBuffer",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~Boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "src/.external-ecmascript.js~DataView",
    "external"
  ],
  [
    "src/.external-ecmascript.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "src/.external-ecmascript.js~Date",
    "external"
  ],
  [
    "src/.external-ecmascript.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "src/.external-ecmascript.js~Error",
    "external"
  ],
  [
    "src/.external-ecmascript.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "src/.external-ecmascript.js~EvalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "src/.external-ecmascript.js~Float32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "src/.external-ecmascript.js~Float64Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~Function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "src/.external-ecmascript.js~Generator",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "src/.external-ecmascript.js~GeneratorFunction",
    "external"
  ],
  [
    "src/.external-ecmascript.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "src/.external-ecmascript.js~Infinity",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "src/.external-ecmascript.js~Int16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "src/.external-ecmascript.js~Int32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "src/.external-ecmascript.js~Int8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "src/.external-ecmascript.js~InternalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "src/.external-ecmascript.js~JSON",
    "external"
  ],
  [
    "src/.external-ecmascript.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "src/.external-ecmascript.js~Map",
    "external"
  ],
  [
    "src/.external-ecmascript.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "src/.external-ecmascript.js~NaN",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~Number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~Object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "src/.external-ecmascript.js~Promise",
    "external"
  ],
  [
    "src/.external-ecmascript.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "src/.external-ecmascript.js~Proxy",
    "external"
  ],
  [
    "src/.external-ecmascript.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "src/.external-ecmascript.js~RangeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "src/.external-ecmascript.js~ReferenceError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "src/.external-ecmascript.js~Reflect",
    "external"
  ],
  [
    "src/.external-ecmascript.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "src/.external-ecmascript.js~RegExp",
    "external"
  ],
  [
    "src/.external-ecmascript.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "src/.external-ecmascript.js~Set",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~String",
    "external"
  ],
  [
    "src/.external-ecmascript.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "src/.external-ecmascript.js~Symbol",
    "external"
  ],
  [
    "src/.external-ecmascript.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "src/.external-ecmascript.js~SyntaxError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "src/.external-ecmascript.js~TypeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "src/.external-ecmascript.js~URIError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "src/.external-ecmascript.js~Uint16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "src/.external-ecmascript.js~Uint32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "src/.external-ecmascript.js~Uint8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "src/.external-ecmascript.js~Uint8ClampedArray",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "src/.external-ecmascript.js~WeakMap",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "src/.external-ecmascript.js~WeakSet",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "src/.external-ecmascript.js~null",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~string",
    "external"
  ],
  [
    "src/.external-ecmascript.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "src/.external-ecmascript.js~undefined",
    "external"
  ],
  [
    "src/app.js",
    "file/src/App.js.html",
    "src/App.js",
    "file"
  ],
  [
    "src/app.test.js",
    "file/src/App.test.js.html",
    "src/App.test.js",
    "file"
  ],
  [
    "src/components/content/carousel/carousel.js",
    "file/src/components/Content/Carousel/Carousel.js.html",
    "src/components/Content/Carousel/Carousel.js",
    "file"
  ],
  [
    "src/components/content/content.js",
    "file/src/components/Content/Content.js.html",
    "src/components/Content/Content.js",
    "file"
  ],
  [
    "src/components/content/workspace/resultarea.js",
    "file/src/components/Content/WorkSpace/ResultArea.js.html",
    "src/components/Content/WorkSpace/ResultArea.js",
    "file"
  ],
  [
    "src/components/content/workspace/resultcompose.js",
    "file/src/components/Content/WorkSpace/ResultCompose.js.html",
    "src/components/Content/WorkSpace/ResultCompose.js",
    "file"
  ],
  [
    "src/components/content/workspace/face-api-func.js",
    "file/src/components/Content/WorkSpace/face-api-func.js.html",
    "src/components/Content/WorkSpace/face-api-func.js",
    "file"
  ],
  [
    "src/components/footer/footer.js",
    "file/src/components/Footer/Footer.js.html",
    "src/components/Footer/Footer.js",
    "file"
  ],
  [
    "src/components/header/header.js",
    "file/src/components/Header/Header.js.html",
    "src/components/Header/Header.js",
    "file"
  ],
  [
    "src/i18n.js",
    "file/src/i18n.js.html",
    "src/i18n.js",
    "file"
  ],
  [
    "src/imports.js",
    "file/src/imports.js.html",
    "src/imports.js",
    "file"
  ],
  [
    "src/index.js",
    "file/src/index.js.html",
    "src/index.js",
    "file"
  ],
  [
    "src/setuptests.js",
    "file/src/setupTests.js.html",
    "src/setupTests.js",
    "file"
  ],
  [
    "src/tools/languageselector.js",
    "file/src/tools/LanguageSelector.js.html",
    "src/tools/LanguageSelector.js",
    "file"
  ],
  [
    "src/tools/usewidth.js",
    "file/src/tools/useWidth.js.html",
    "src/tools/useWidth.js",
    "file"
  ]
]